export const UPDATE_SALE_BY_ID = 'UPDATE_SALE_BY_ID';
export const FILTER_ALL_SALE_DATA = 'FILTER_ALL_SALE_DATA';
export const FILTER_BY_SALE_PRODUCT_NAME = 'FILTER_BY_SALE_PRODUCT_NAME';
export const FILTER_BY_CUSTOMER = 'FILTER_BY_CUSTOMER';
export const FILTER_BY_SALE_DATE = 'FILTER_BY_SALE_DATE';
export const SALE_FILTER_SCREEN_VISIBLE = 'SALE_FILTER_SCREEN_VISIBLE';
export const IS_SALE_FLATLIST_REFRESHED = 'IS_SALE_FLATLIST_REFRESHED';
